import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { Button } from "@nextui-org/react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import HomeNavbar from "~/components/Navbar";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const listings = api.listings.list.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <HomeNavbar /> */}
      <main className="flex min-h-screen pt-[6rem]  ">
        <div className="flex flex-wrap w-11/12 mx-auto items-center justify-center gap-4">
          {
            listings?.data?.map((e) =>
              <Link key={e.id} href={`/${e.id}`}>
                <div key={e.id} className=" gap-2 flex items-center justify-center flex-col p-2 w-fit border rounded-md">
                  <div className="bg-black rounded w-64 aspect-square"></div>
                  <div>{e.name}</div>
                  <Button shadow className="mb-2">${e.price}</Button>
                </div>
              </Link>
            )
          }

        </div>
      </main>
    </>
  );
};

export default Home;
