import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { Button, Loading } from "@nextui-org/react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import HomeNavbar from "~/components/Navbar";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: listings, isLoading } = api.listings.list.useQuery();
  console.log(listings)
  type Inputs = {
    id: string
    name: string;
    description: string;
    price: number;
    image: string
  };
  if (isLoading) {

    return (
      <div className='pt-[6rem] flex min-h-screen items-center justify-center'><Loading /></div>
    )
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen pt-[6rem]  ">
        <div className="flex flex-wrap w-11/12 mx-auto items-center justify-center gap-4">
          {
            listings?.map((e: Inputs) =>
              <Link key={e.id} href={`/${e.id}`}>
                <div key={e.id} className=" gap-2 flex items-center justify-center flex-col p-2 w-fit border rounded-md">
                  <img src={e.image} className="rounded w-48 aspect-square" />
                  <div>{e.name}</div>
                  <Button size={'sm'} flat className="w-fit mb-2">${e.price}</Button>
                </div>
              </Link>
            )
          }

        </div>
      </main>
    </>
  );
};

export default Home;
